---
title: "SOS"
author: "MD"
date: '2022-08-10'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(patchwork)
library(ggbeeswarm)
library(kableExtra)
library(magrittr)
theme_set(theme_classic())
```

```{r dataload}
SOSdata <-read_csv("N2_SOS_09142022")
SOSdata$Bacteria <-factor(SOSdata$Bacteria, levels = c("OP50", "JUb39"), ordered = TRUE)

```
```{r graphs}
(N2_SOS_09142022 <-SOSdata %>%
  ggplot(aes(x=Bacteria, y='Time'))+
  barplot (as.matrix()) +
  ggbeeswarm::geom_quasirandom(aes(group =Genotype), width = 0.1, alpha = 0.3, dodge.width = 0.75)+
  stat_summary(aes(fill=Genotype),geom = "errorbar", fun.data = "mean_se", width = 0.1, position = position_dodge(width = 0.75))+
  labs(title = "", y = "reversal time (s)")+
   scale_fill_brewer(palette = "Set1"))

(N2_SOS_09142022 <- SOSdata %>% 
 ggplot(aes(x = Bacteria, y = `Time`)) +
    ggbeeswarm::geom_quasirandom(width = 0.1, alpha = 0.3) +
    stat_summary(geom = "errorbar", fun.data = "mean_cl_boot", width = 0.1) +
    stat_summary(geom = "crossbar", fun = "median", width = 0.3,fatten = 1.5) +
  facet_grid(.~Bacteria))

```
```{r}

(N2_SOS_09142022 <- SOSdata %>% 
 ggplot(aes(x = Bacteria, y = `Time`)) +
    ggbeeswarm::geom_quasirandom(width = 0.1, alpha = 0.3) +
    stat_summary(geom = "errorbar", fun.data = "mean_cl_boot", width = 0.1) +
    stat_summary(geom = "crossbar", fun = "median", width = 0.3,fatten = 1.5) +
  facet_grid(.~Bacteria))



